# Configuration for PR path-based labeling (actions/labeler)
build:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'
          - 'Taskfile.yml'
          - 'go.mod'
          - 'go.sum'
          - 'scripts/**'

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/**'
          - '*.md'
          - 'LICENSE'

area:core:
  - changed-files:
      - any-glob-to-any-file:
          - '*.go'
          - 'pkg/engine/**'

area:cli:
  - changed-files:
      - any-glob-to-any-file:
          - 'cmd/**'

area:plugins:
  - changed-files:
      - any-glob-to-any-file:
          - 'cmd/plugins/**'
          - 'pkg/addons/**'

area:voip:
  - changed-files:
      - any-glob-to-any-file:
          - 'pkg/engine/mlow/**'
          - 'pkg/engine/rtp/**'
          - 'pkg/engine/srtp/**'
          - 'pkg/engine/stun/**'
          - 'pkg/engine/call*.go'

area:utils:
  - changed-files:
      - any-glob-to-any-file:
          - 'util/**'
          - 'cmd/utils/**'

area:sdk:
  - changed-files:
      - any-glob-to-any-file:
          - 'pkg/addons/sdk/**'

