package utils

// Predefined Windows and IANA timezone entries.
var tzEntries = []WindowsTZEntry{
	{
		Value:  "Dateline Standard Time",
		Abbr:   "DST",
		Offset: -12,
		IsDST:  false,
		Text:   "(UTC-12:00) International Date Line West",
		UTC:    []string{"Etc/GMT+12"},
	},
	{
		Value:  "UTC-11",
		Abbr:   "U",
		Offset: -11,
		IsDST:  false,
		Text:   "(UTC-11:00) Coordinated Universal Time-11",
		UTC:    []string{"Etc/GMT+11", "Pacific/Midway", "Pacific/Niue", "Pacific/Pago_Pago"},
	},
	{
		Value:  "Hawaiian Standard Time",
		Abbr:   "HST",
		Offset: -10,
		IsDST:  false,
		Text:   "(UTC-10:00) Hawaii",
		UTC:    []string{"Etc/GMT+10", "Pacific/Honolulu", "Pacific/Johnston", "Pacific/Rarotonga", "Pacific/Tahiti"},
	},
	{
		Value:  "Alaskan Standard Time",
		Abbr:   "AKDT",
		Offset: -8,
		IsDST:  true,
		Text:   "(UTC-09:00) Alaska",
		UTC:    []string{"America/Anchorage", "America/Juneau", "America/Nome", "America/Sitka", "America/Yakutat"},
	},
	{
		Value:  "Pacific Standard Time (Mexico)",
		Abbr:   "PDT",
		Offset: -7,
		IsDST:  true,
		Text:   "(UTC-08:00) Baja California",
		UTC:    []string{"America/Santa_Isabel"},
	},
	{
		Value:  "Pacific Daylight Time",
		Abbr:   "PDT",
		Offset: -7,
		IsDST:  true,
		Text:   "(UTC-07:00) Pacific Daylight Time (US & Canada)",
		UTC:    []string{"America/Los_Angeles", "America/Tijuana", "America/Vancouver"},
	},
	{
		Value:  "Pacific Standard Time",
		Abbr:   "PST",
		Offset: -8,
		IsDST:  false,
		Text:   "(UTC-08:00) Pacific Standard Time (US & Canada)",
		UTC:    []string{"America/Los_Angeles", "America/Tijuana", "America/Vancouver", "PST8PDT"},
	},
	{
		Value:  "US Mountain Standard Time",
		Abbr:   "UMST",
		Offset: -7,
		IsDST:  false,
		Text:   "(UTC-07:00) Arizona",
		UTC:    []string{"America/Creston", "America/Dawson", "America/Dawson_Creek", "America/Hermosillo", "America/Phoenix", "America/Whitehorse", "Etc/GMT+7"},
	},
	{
		Value:  "Mountain Standard Time (Mexico)",
		Abbr:   "MDT",
		Offset: -6,
		IsDST:  true,
		Text:   "(UTC-07:00) Chihuahua, La Paz, Mazatlan",
		UTC:    []string{"America/Chihuahua", "America/Mazatlan"},
	},
	{
		Value:  "Mountain Standard Time",
		Abbr:   "MDT",
		Offset: -6,
		IsDST:  true,
		Text:   "(UTC-07:00) Mountain Time (US & Canada)",
		UTC:    []string{"America/Boise", "America/Cambridge_Bay", "America/Denver", "America/Edmonton", "America/Inuvik", "America/Ojinaga", "America/Yellowknife", "MST7MDT"},
	},
	{
		Value:  "Central America Standard Time",
		Abbr:   "CAST",
		Offset: -6,
		IsDST:  false,
		Text:   "(UTC-06:00) Central America",
		UTC:    []string{"America/Belize", "America/Costa_Rica", "America/El_Salvador", "America/Guatemala", "America/Managua", "America/Tegucigalpa", "Etc/GMT+6", "Pacific/Galapagos"},
	},
	{
		Value:  "Central Standard Time",
		Abbr:   "CDT",
		Offset: -5,
		IsDST:  true,
		Text:   "(UTC-06:00) Central Time (US & Canada)",
		UTC:    []string{"America/Chicago", "America/Indiana/Knox", "America/Indiana/Tell_City", "America/Matamoros", "America/Menominee", "America/North_Dakota/Beulah", "America/North_Dakota/Center", "America/North_Dakota/New_Salem", "America/Rainy_River", "America/Rankin_Inlet", "America/Resolute", "America/Winnipeg", "CST6CDT"},
	},
	{
		Value:  "Central Standard Time (Mexico)",
		Abbr:   "CDT",
		Offset: -5,
		IsDST:  true,
		Text:   "(UTC-06:00) Guadalajara, Mexico City, Monterrey",
		UTC:    []string{"America/Bahia_Banderas", "America/Cancun", "America/Merida", "America/Mexico_City", "America/Monterrey"},
	},
	{
		Value:  "Canada Central Standard Time",
		Abbr:   "CCST",
		Offset: -6,
		IsDST:  false,
		Text:   "(UTC-06:00) Saskatchewan",
		UTC:    []string{"America/Regina", "America/Swift_Current"},
	},
	{
		Value:  "SA Pacific Standard Time",
		Abbr:   "SPST",
		Offset: -5,
		IsDST:  false,
		Text:   "(UTC-05:00) Bogota, Lima, Quito",
		UTC:    []string{"America/Bogota", "America/Cayman", "America/Coral_Harbour", "America/Eirunepe", "America/Guayaquil", "America/Jamaica", "America/Lima", "America/Panama", "America/Rio_Branco", "Etc/GMT+5"},
	},
	{
		Value:  "Eastern Standard Time",
		Abbr:   "EST",
		Offset: -5,
		IsDST:  false,
		Text:   "(UTC-05:00) Eastern Time (US & Canada)",
		UTC:    []string{"America/Detroit", "America/Havana", "America/Indiana/Petersburg", "America/Indiana/Vincennes", "America/Indiana/Winamac", "America/Iqaluit", "America/Kentucky/Monticello", "America/Louisville", "America/Montreal", "America/Nassau", "America/New_York", "America/Nipigon", "America/Pangnirtung", "America/Port-au-Prince", "America/Thunder_Bay", "America/Toronto"},
	},
	{
		Value:  "Eastern Daylight Time",
		Abbr:   "EDT",
		Offset: -4,
		IsDST:  true,
		Text:   "(UTC-04:00) Eastern Daylight Time (US & Canada)",
		UTC:    []string{"America/Detroit", "America/Havana", "America/Indiana/Petersburg", "America/Indiana/Vincennes", "America/Indiana/Winamac", "America/Iqaluit", "America/Kentucky/Monticello", "America/Louisville", "America/Montreal", "America/Nassau", "America/New_York", "America/Nipigon", "America/Pangnirtung", "America/Port-au-Prince", "America/Thunder_Bay", "America/Toronto"},
	},
	{
		Value:  "US Eastern Standard Time",
		Abbr:   "UEDT",
		Offset: -5,
		IsDST:  false,
		Text:   "(UTC-05:00) Indiana (East)",
		UTC:    []string{"America/Indiana/Marengo", "America/Indiana/Vevay", "America/Indianapolis"},
	},
	{
		Value:  "Venezuela Standard Time",
		Abbr:   "VST",
		Offset: -4.5,
		IsDST:  false,
		Text:   "(UTC-04:30) Caracas",
		UTC:    []string{"America/Caracas"},
	},
	{
		Value:  "Paraguay Standard Time",
		Abbr:   "PYT",
		Offset: -4,
		IsDST:  false,
		Text:   "(UTC-04:00) Asuncion",
		UTC:    []string{"America/Asuncion"},
	},
	{
		Value:  "Atlantic Standard Time",
		Abbr:   "ADT",
		Offset: -3,
		IsDST:  true,
		Text:   "(UTC-04:00) Atlantic Time (Canada)",
		UTC:    []string{"America/Glace_Bay", "America/Goose_Bay", "America/Halifax", "America/Moncton", "America/Thule", "Atlantic/Bermuda"},
	},
	{
		Value:  "Central Brazilian Standard Time",
		Abbr:   "CBST",
		Offset: -4,
		IsDST:  false,
		Text:   "(UTC-04:00) Cuiaba",
		UTC:    []string{"America/Campo_Grande", "America/Cuiaba"},
	},
	{
		Value:  "SA Western Standard Time",
		Abbr:   "SWST",
		Offset: -4,
		IsDST:  false,
		Text:   "(UTC-04:00) Georgetown, La Paz, Manaus, San Juan",
		UTC:    []string{"America/Anguilla", "America/Antigua", "America/Aruba", "America/Barbados", "America/Blanc-Sablon", "America/Boa_Vista", "America/Curacao", "America/Dominica", "America/Grand_Turk", "America/Grenada", "America/Guadeloupe", "America/Guyana", "America/Kralendijk", "America/La_Paz", "America/Lower_Princes", "America/Manaus", "America/Marigot", "America/Martinique", "America/Montserrat", "America/Port_of_Spain", "America/Porto_Velho", "America/Puerto_Rico", "America/Santo_Domingo", "America/St_Barthelemy", "America/St_Kitts", "America/St_Lucia", "America/St_Thomas", "America/St_Vincent", "America/Tortola", "Etc/GMT+4"},
	},
	{
		Value:  "Pacific SA Standard Time",
		Abbr:   "PSST",
		Offset: -4,
		IsDST:  false,
		Text:   "(UTC-04:00) Santiago",
		UTC:    []string{"America/Santiago", "Antarctica/Palmer"},
	},
	{
		Value:  "Newfoundland Standard Time",
		Abbr:   "NDT",
		Offset: -2.5,
		IsDST:  true,
		Text:   "(UTC-03:30) Newfoundland",
		UTC:    []string{"America/St_Johns"},
	},
	{
		Value:  "E. South America Standard Time",
		Abbr:   "ESAST",
		Offset: -3,
		IsDST:  false,
		Text:   "(UTC-03:00) Brasilia",
		UTC:    []string{"America/Sao_Paulo"},
	},
	{
		Value:  "Argentina Standard Time",
		Abbr:   "AST",
		Offset: -3,
		IsDST:  false,
		Text:   "(UTC-03:00) Buenos Aires",
		UTC:    []string{"America/Argentina/Buenos_Aires", "America/Argentina/Catamarca", "America/Argentina/Cordoba", "America/Argentina/Jujuy", "America/Argentina/La_Rioja", "America/Argentina/Mendoza", "America/Argentina/Rio_Gallegos", "America/Argentina/Salta", "America/Argentina/San_Juan", "America/Argentina/San_Luis", "America/Argentina/Tucuman", "America/Argentina/Ushuaia", "America/Buenos_Aires", "America/Catamarca", "America/Cordoba", "America/Jujuy", "America/Mendoza"},
	},
	{
		Value:  "SA Eastern Standard Time",
		Abbr:   "SEST",
		Offset: -3,
		IsDST:  false,
		Text:   "(UTC-03:00) Cayenne, Fortaleza",
		UTC:    []string{"America/Araguaina", "America/Belem", "America/Cayenne", "America/Fortaleza", "America/Maceio", "America/Paramaribo", "America/Recife", "America/Santarem", "Antarctica/Rothera", "Atlantic/Stanley", "Etc/GMT+3"},
	},
	{
		Value:  "Greenland Standard Time",
		Abbr:   "GDT",
		Offset: -3,
		IsDST:  true,
		Text:   "(UTC-03:00) Greenland",
		UTC:    []string{"America/Godthab"},
	},
	{
		Value:  "Montevideo Standard Time",
		Abbr:   "MST",
		Offset: -3,
		IsDST:  false,
		Text:   "(UTC-03:00) Montevideo",
		UTC:    []string{"America/Montevideo"},
	},
	{
		Value:  "Bahia Standard Time",
		Abbr:   "BST",
		Offset: -3,
		IsDST:  false,
		Text:   "(UTC-03:00) Salvador",
		UTC:    []string{"America/Bahia"},
	},
	{
		Value:  "UTC-02",
		Abbr:   "U",
		Offset: -2,
		IsDST:  false,
		Text:   "(UTC-02:00) Coordinated Universal Time-02",
		UTC:    []string{"America/Noronha", "Atlantic/South_Georgia", "Etc/GMT+2"},
	},
	{
		Value:  "Mid-Atlantic Standard Time",
		Abbr:   "MDT",
		Offset: -1,
		IsDST:  true,
		Text:   "(UTC-02:00) Mid-Atlantic - Old",
		UTC:    []string{},
	},
	{
		Value:  "Azores Standard Time",
		Abbr:   "ADT",
		Offset: 0,
		IsDST:  true,
		Text:   "(UTC-01:00) Azores",
		UTC:    []string{"America/Scoresbysund", "Atlantic/Azores"},
	},
	{
		Value:  "Cape Verde Standard Time",
		Abbr:   "CVST",
		Offset: -1,
		IsDST:  false,
		Text:   "(UTC-01:00) Cape Verde Is.",
		UTC:    []string{"Atlantic/Cape_Verde", "Etc/GMT+1"},
	},
	{
		Value:  "Morocco Standard Time",
		Abbr:   "MDT",
		Offset: 1,
		IsDST:  true,
		Text:   "(UTC) Casablanca",
		UTC:    []string{"Africa/Casablanca", "Africa/El_Aaiun"},
	},
	{
		Value:  "UTC",
		Abbr:   "UTC",
		Offset: 0,
		IsDST:  false,
		Text:   "(UTC) Coordinated Universal Time",
		UTC:    []string{"America/Danmarkshavn", "Etc/GMT"},
	},
	{
		Value:  "GMT Standard Time",
		Abbr:   "GMT",
		Offset: 0,
		IsDST:  false,
		Text:   "(UTC) Edinburgh, London",
		UTC:    []string{"Europe/Isle_of_Man", "Europe/Guernsey", "Europe/Jersey", "Europe/London"},
	},
	{
		Value:  "British Summer Time",
		Abbr:   "BST",
		Offset: 1,
		IsDST:  true,
		Text:   "(UTC+01:00) Edinburgh, London",
		UTC:    []string{"Europe/Isle_of_Man", "Europe/Guernsey", "Europe/Jersey", "Europe/London"},
	},
	{
		Value:  "GMT Standard Time",
		Abbr:   "GDT",
		Offset: 1,
		IsDST:  true,
		Text:   "(UTC) Dublin, Lisbon",
		UTC:    []string{"Atlantic/Canary", "Atlantic/Faeroe", "Atlantic/Madeira", "Europe/Dublin", "Europe/Lisbon"},
	},
	{
		Value:  "Greenwich Standard Time",
		Abbr:   "GST",
		Offset: 0,
		IsDST:  false,
		Text:   "(UTC) Monrovia, Reykjavik",
		UTC:    []string{"Africa/Abidjan", "Africa/Accra", "Africa/Bamako", "Africa/Banjul", "Africa/Bissau", "Africa/Conakry", "Africa/Dakar", "Africa/Freetown", "Africa/Lome", "Africa/Monrovia", "Africa/Nouakchott", "Africa/Ouagadougou", "Africa/Sao_Tome", "Atlantic/Reykjavik", "Atlantic/St_Helena"},
	},
	{
		Value:  "W. Europe Standard Time",
		Abbr:   "WEDT",
		Offset: 2,
		IsDST:  true,
		Text:   "(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
		UTC:    []string{"Arctic/Longyearbyen", "Europe/Amsterdam", "Europe/Andorra", "Europe/Berlin", "Europe/Busingen", "Europe/Gibraltar", "Europe/Luxembourg", "Europe/Malta", "Europe/Monaco", "Europe/Oslo", "Europe/Rome", "Europe/San_Marino", "Europe/Stockholm", "Europe/Vaduz", "Europe/Vatican", "Europe/Vienna", "Europe/Zurich"},
	},
	{
		Value:  "Central Europe Standard Time",
		Abbr:   "CEDT",
		Offset: 2,
		IsDST:  true,
		Text:   "(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague",
		UTC:    []string{"Europe/Belgrade", "Europe/Bratislava", "Europe/Budapest", "Europe/Ljubljana", "Europe/Podgorica", "Europe/Prague", "Europe/Tirane"},
	},
	{
		Value:  "Romance Standard Time",
		Abbr:   "RDT",
		Offset: 2,
		IsDST:  true,
		Text:   "(UTC+01:00) Brussels, Copenhagen, Madrid, Paris",
		UTC:    []string{"Africa/Ceuta", "Europe/Brussels", "Europe/Copenhagen", "Europe/Madrid", "Europe/Paris"},
	},
	{
		Value:  "Central European Standard Time",
		Abbr:   "CEDT",
		Offset: 2,
		IsDST:  true,
		Text:   "(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb",
		UTC:    []string{"Europe/Sarajevo", "Europe/Skopje", "Europe/Warsaw", "Europe/Zagreb"},
	},
	{
		Value:  "W. Central Africa Standard Time",
		Abbr:   "WCAST",
		Offset: 1,
		IsDST:  false,
		Text:   "(UTC+01:00) West Central Africa",
		UTC:    []string{"Africa/Algiers", "Africa/Bangui", "Africa/Brazzaville", "Africa/Douala", "Africa/Kinshasa", "Africa/Lagos", "Africa/Libreville", "Africa/Luanda", "Africa/Malabo", "Africa/Ndjamena", "Africa/Niamey", "Africa/Porto-Novo", "Africa/Tunis", "Etc/GMT-1"},
	},
	{
		Value:  "Namibia Standard Time",
		Abbr:   "NST",
		Offset: 1,
		IsDST:  false,
		Text:   "(UTC+01:00) Windhoek",
		UTC:    []string{"Africa/Windhoek"},
	},
	{
		Value:  "GTB Standard Time",
		Abbr:   "GDT",
		Offset: 3,
		IsDST:  true,
		Text:   "(UTC+02:00) Athens, Bucharest",
		UTC:    []string{"Asia/Nicosia", "Europe/Athens", "Europe/Bucharest", "Europe/Chisinau"},
	},
	{
		Value:  "Middle East Standard Time",
		Abbr:   "MEDT",
		Offset: 3,
		IsDST:  true,
		Text:   "(UTC+02:00) Beirut",
		UTC:    []string{"Asia/Beirut"},
	},
	{
		Value:  "Egypt Standard Time",
		Abbr:   "EST",
		Offset: 2,
		IsDST:  false,
		Text:   "(UTC+02:00) Cairo",
		UTC:    []string{"Africa/Cairo"},
	},
	{
		Value:  "Syria Standard Time",
		Abbr:   "SDT",
		Offset: 3,
		IsDST:  false,
		Text:   "(UTC+02:00) Damascus",
		UTC:    []string{"Asia/Damascus"},
	},
	{
		Value:  "E. Europe Standard Time",
		Abbr:   "EEDT",
		Offset: 3,
		IsDST:  true,
		Text:   "(UTC+02:00) E. Europe",
		UTC:    []string{"Asia/Nicosia", "Europe/Athens", "Europe/Bucharest", "Europe/Chisinau", "Europe/Helsinki", "Europe/Kyiv", "Europe/Mariehamn", "Europe/Nicosia", "Europe/Riga", "Europe/Sofia", "Europe/Tallinn", "Europe/Uzhhorod", "Europe/Vilnius", "Europe/Zaporizhzhia"},
	},
	{
		Value:  "South Africa Standard Time",
		Abbr:   "SAST",
		Offset: 2,
		IsDST:  false,
		Text:   "(UTC+02:00) Harare, Pretoria",
		UTC:    []string{"Africa/Blantyre", "Africa/Bujumbura", "Africa/Gaborone", "Africa/Harare", "Africa/Johannesburg", "Africa/Kigali", "Africa/Lubumbashi", "Africa/Lusaka", "Africa/Maputo", "Africa/Maseru", "Africa/Mbabane", "Etc/GMT-2"},
	},
	{
		Value:  "FLE Standard Time",
		Abbr:   "FDT",
		Offset: 3,
		IsDST:  true,
		Text:   "(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius",
		UTC:    []string{"Europe/Helsinki", "Europe/Kyiv", "Europe/Mariehamn", "Europe/Riga", "Europe/Sofia", "Europe/Tallinn", "Europe/Uzhhorod", "Europe/Vilnius", "Europe/Zaporizhzhia"},
	},
	{
		Value:  "Turkey Standard Time",
		Abbr:   "TDT",
		Offset: 3,
		IsDST:  false,
		Text:   "(UTC+03:00) Istanbul",
		UTC:    []string{"Europe/Istanbul"},
	},
	{
		Value:  "Israel Standard Time",
		Abbr:   "JDT",
		Offset: 3,
		IsDST:  true,
		Text:   "(UTC+02:00) Jerusalem",
		UTC:    []string{"Asia/Jerusalem"},
	},
	{
		Value:  "Libya Standard Time",
		Abbr:   "LST",
		Offset: 2,
		IsDST:  false,
		Text:   "(UTC+02:00) Tripoli",
		UTC:    []string{"Africa/Tripoli"},
	},
	{
		Value:  "Jordan Standard Time",
		Abbr:   "JST",
		Offset: 3,
		IsDST:  false,
		Text:   "(UTC+03:00) Amman",
		UTC:    []string{"Asia/Amman"},
	},
	{
		Value:  "Arabic Standard Time",
		Abbr:   "AST",
		Offset: 3,
		IsDST:  false,
		Text:   "(UTC+03:00) Baghdad",
		UTC:    []string{"Asia/Baghdad"},
	},
	{
		Value:  "Kaliningrad Standard Time",
		Abbr:   "KST",
		Offset: 3,
		IsDST:  false,
		Text:   "(UTC+02:00) Kaliningrad",
		UTC:    []string{"Europe/Kaliningrad"},
	},
	{
		Value:  "Arab Standard Time",
		Abbr:   "AST",
		Offset: 3,
		IsDST:  false,
		Text:   "(UTC+03:00) Kuwait, Riyadh",
		UTC:    []string{"Asia/Aden", "Asia/Bahrain", "Asia/Kuwait", "Asia/Qatar", "Asia/Riyadh"},
	},
	{
		Value:  "E. Africa Standard Time",
		Abbr:   "EAST",
		Offset: 3,
		IsDST:  false,
		Text:   "(UTC+03:00) Nairobi",
		UTC:    []string{"Africa/Addis_Ababa", "Africa/Asmera", "Africa/Dar_es_Salaam", "Africa/Djibouti", "Africa/Juba", "Africa/Kampala", "Africa/Khartoum", "Africa/Mogadishu", "Africa/Nairobi", "Antarctica/Syowa", "Etc/GMT-3", "Indian/Antananarivo", "Indian/Comoro", "Indian/Mayotte"},
	},
	{
		Value:  "Moscow Standard Time",
		Abbr:   "MSK",
		Offset: 3,
		IsDST:  false,
		Text:   "(UTC+03:00) Moscow, St. Petersburg, Volgograd, Minsk",
		UTC:    []string{"Europe/Kirov", "Europe/Moscow", "Europe/Simferopol", "Europe/Volgograd", "Europe/Minsk"},
	},
	{
		Value:  "Samara Time",
		Abbr:   "SAMT",
		Offset: 4,
		IsDST:  false,
		Text:   "(UTC+04:00) Samara, Ulyanovsk, Saratov",
		UTC:    []string{"Europe/Astrakhan", "Europe/Samara", "Europe/Ulyanovsk"},
	},
	{
		Value:  "Iran Standard Time",
		Abbr:   "IDT",
		Offset: 4.5,
		IsDST:  true,
		Text:   "(UTC+03:30) Tehran",
		UTC:    []string{"Asia/Tehran"},
	},
	{
		Value:  "Arabian Standard Time",
		Abbr:   "AST",
		Offset: 4,
		IsDST:  false,
		Text:   "(UTC+04:00) Abu Dhabi, Muscat",
		UTC:    []string{"Asia/Dubai", "Asia/Muscat", "Etc/GMT-4"},
	},
	{
		Value:  "Azerbaijan Standard Time",
		Abbr:   "ADT",
		Offset: 5,
		IsDST:  true,
		Text:   "(UTC+04:00) Baku",
		UTC:    []string{"Asia/Baku"},
	},
	{
		Value:  "Mauritius Standard Time",
		Abbr:   "MST",
		Offset: 4,
		IsDST:  false,
		Text:   "(UTC+04:00) Port Louis",
		UTC:    []string{"Indian/Mahe", "Indian/Mauritius", "Indian/Reunion"},
	},
	{
		Value:  "Georgian Standard Time",
		Abbr:   "GET",
		Offset: 4,
		IsDST:  false,
		Text:   "(UTC+04:00) Tbilisi",
		UTC:    []string{"Asia/Tbilisi"},
	},
	{
		Value:  "Caucasus Standard Time",
		Abbr:   "CST",
		Offset: 4,
		IsDST:  false,
		Text:   "(UTC+04:00) Yerevan",
		UTC:    []string{"Asia/Yerevan"},
	},
	{
		Value:  "Afghanistan Standard Time",
		Abbr:   "AST",
		Offset: 4.5,
		IsDST:  false,
		Text:   "(UTC+04:30) Kabul",
		UTC:    []string{"Asia/Kabul"},
	},
	{
		Value:  "West Asia Standard Time",
		Abbr:   "WAST",
		Offset: 5,
		IsDST:  false,
		Text:   "(UTC+05:00) Ashgabat, Tashkent",
		UTC:    []string{"Antarctica/Mawson", "Asia/Aqtau", "Asia/Aqtobe", "Asia/Ashgabat", "Asia/Dushanbe", "Asia/Oral", "Asia/Samarkand", "Asia/Tashkent", "Etc/GMT-5", "Indian/Kerguelen", "Indian/Maldives"},
	},
	{
		Value:  "Yekaterinburg Time",
		Abbr:   "YEKT",
		Offset: 5,
		IsDST:  false,
		Text:   "(UTC+05:00) Yekaterinburg",
		UTC:    []string{"Asia/Yekaterinburg"},
	},
	{
		Value:  "Pakistan Standard Time",
		Abbr:   "PKT",
		Offset: 5,
		IsDST:  false,
		Text:   "(UTC+05:00) Islamabad, Karachi",
		UTC:    []string{"Asia/Karachi"},
	},
	{
		Value:  "India Standard Time",
		Abbr:   "IST",
		Offset: 5.5,
		IsDST:  false,
		Text:   "(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi",
		UTC:    []string{"Asia/Kolkata", "Asia/Calcutta"},
	},
	{
		Value:  "Sri Lanka Standard Time",
		Abbr:   "SLST",
		Offset: 5.5,
		IsDST:  false,
		Text:   "(UTC+05:30) Sri Jayawardenepura",
		UTC:    []string{"Asia/Colombo"},
	},
	{
		Value:  "Nepal Standard Time",
		Abbr:   "NST",
		Offset: 5.75,
		IsDST:  false,
		Text:   "(UTC+05:45) Kathmandu",
		UTC:    []string{"Asia/Kathmandu"},
	},
	{
		Value:  "Central Asia Standard Time",
		Abbr:   "CAST",
		Offset: 6,
		IsDST:  false,
		Text:   "(UTC+06:00) Nur-Sultan (Astana)",
		UTC:    []string{"Antarctica/Vostok", "Asia/Almaty", "Asia/Bishkek", "Asia/Qyzylorda", "Asia/Urumqi", "Etc/GMT-6", "Indian/Chagos"},
	},
	{
		Value:  "Bangladesh Standard Time",
		Abbr:   "BST",
		Offset: 6,
		IsDST:  false,
		Text:   "(UTC+06:00) Dhaka",
		UTC:    []string{"Asia/Dhaka", "Asia/Thimphu"},
	},
	{
		Value:  "Myanmar Standard Time",
		Abbr:   "MST",
		Offset: 6.5,
		IsDST:  false,
		Text:   "(UTC+06:30) Yangon (Rangoon)",
		UTC:    []string{"Asia/Rangoon", "Indian/Cocos"},
	},
	{
		Value:  "SE Asia Standard Time",
		Abbr:   "SAST",
		Offset: 7,
		IsDST:  false,
		Text:   "(UTC+07:00) Bangkok, Hanoi, Jakarta",
		UTC:    []string{"Antarctica/Davis", "Asia/Bangkok", "Asia/Hovd", "Asia/Jakarta", "Asia/Phnom_Penh", "Asia/Pontianak", "Asia/Saigon", "Asia/Vientiane", "Etc/GMT-7", "Indian/Christmas"},
	},
	{
		Value:  "N. Central Asia Standard Time",
		Abbr:   "NCAST",
		Offset: 7,
		IsDST:  false,
		Text:   "(UTC+07:00) Novosibirsk",
		UTC:    []string{"Asia/Novokuznetsk", "Asia/Novosibirsk", "Asia/Omsk", "Asia/Tomsk"},
	},
	{
		Value:  "China Standard Time",
		Abbr:   "CST",
		Offset: 8,
		IsDST:  false,
		Text:   "(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi",
		UTC:    []string{"Asia/Hong_Kong", "Asia/Macau", "Asia/Shanghai"},
	},
	{
		Value:  "North Asia Standard Time",
		Abbr:   "NAST",
		Offset: 8,
		IsDST:  false,
		Text:   "(UTC+08:00) Krasnoyarsk",
		UTC:    []string{"Asia/Krasnoyarsk"},
	},
	{
		Value:  "Singapore Standard Time",
		Abbr:   "MPST",
		Offset: 8,
		IsDST:  false,
		Text:   "(UTC+08:00) Kuala Lumpur, Singapore",
		UTC:    []string{"Asia/Brunei", "Asia/Kuala_Lumpur", "Asia/Kuching", "Asia/Makassar", "Asia/Manila", "Asia/Singapore", "Etc/GMT-8"},
	},
	{
		Value:  "W. Australia Standard Time",
		Abbr:   "WAST",
		Offset: 8,
		IsDST:  false,
		Text:   "(UTC+08:00) Perth",
		UTC:    []string{"Antarctica/Casey", "Australia/Perth"},
	},
	{
		Value:  "Taipei Standard Time",
		Abbr:   "TST",
		Offset: 8,
		IsDST:  false,
		Text:   "(UTC+08:00) Taipei",
		UTC:    []string{"Asia/Taipei"},
	},
	{
		Value:  "Ulaanbaatar Standard Time",
		Abbr:   "UST",
		Offset: 8,
		IsDST:  false,
		Text:   "(UTC+08:00) Ulaanbaatar",
		UTC:    []string{"Asia/Choibalsan", "Asia/Ulaanbaatar"},
	},
	{
		Value:  "North Asia East Standard Time",
		Abbr:   "NAEST",
		Offset: 8,
		IsDST:  false,
		Text:   "(UTC+08:00) Irkutsk",
		UTC:    []string{"Asia/Irkutsk"},
	},
	{
		Value:  "Japan Standard Time",
		Abbr:   "JST",
		Offset: 9,
		IsDST:  false,
		Text:   "(UTC+09:00) Osaka, Sapporo, Tokyo",
		UTC:    []string{"Asia/Dili", "Asia/Jayapura", "Asia/Tokyo", "Etc/GMT-9", "Pacific/Palau"},
	},
	{
		Value:  "Korea Standard Time",
		Abbr:   "KST",
		Offset: 9,
		IsDST:  false,
		Text:   "(UTC+09:00) Seoul",
		UTC:    []string{"Asia/Pyongyang", "Asia/Seoul"},
	},
	{
		Value:  "Cen. Australia Standard Time",
		Abbr:   "CAST",
		Offset: 9.5,
		IsDST:  false,
		Text:   "(UTC+09:30) Adelaide",
		UTC:    []string{"Australia/Adelaide", "Australia/Broken_Hill"},
	},
	{
		Value:  "AUS Central Standard Time",
		Abbr:   "ACST",
		Offset: 9.5,
		IsDST:  false,
		Text:   "(UTC+09:30) Darwin",
		UTC:    []string{"Australia/Darwin"},
	},
	{
		Value:  "E. Australia Standard Time",
		Abbr:   "EAST",
		Offset: 10,
		IsDST:  false,
		Text:   "(UTC+10:00) Brisbane",
		UTC:    []string{"Australia/Brisbane", "Australia/Lindeman"},
	},
	{
		Value:  "AUS Eastern Standard Time",
		Abbr:   "AEST",
		Offset: 10,
		IsDST:  false,
		Text:   "(UTC+10:00) Canberra, Melbourne, Sydney",
		UTC:    []string{"Australia/Melbourne", "Australia/Sydney"},
	},
	{
		Value:  "West Pacific Standard Time",
		Abbr:   "WPST",
		Offset: 10,
		IsDST:  false,
		Text:   "(UTC+10:00) Guam, Port Moresby",
		UTC:    []string{"Antarctica/DumontDUrville", "Etc/GMT-10", "Pacific/Guam", "Pacific/Port_Moresby", "Pacific/Saipan", "Pacific/Truk"},
	},
	{
		Value:  "Tasmania Standard Time",
		Abbr:   "TST",
		Offset: 10,
		IsDST:  false,
		Text:   "(UTC+10:00) Hobart",
		UTC:    []string{"Australia/Currie", "Australia/Hobart"},
	},
	{
		Value:  "Yakutsk Standard Time",
		Abbr:   "YST",
		Offset: 9,
		IsDST:  false,
		Text:   "(UTC+09:00) Yakutsk",
		UTC:    []string{"Asia/Chita", "Asia/Khandyga", "Asia/Yakutsk"},
	},
	{
		Value:  "Central Pacific Standard Time",
		Abbr:   "CPST",
		Offset: 11,
		IsDST:  false,
		Text:   "(UTC+11:00) Solomon Is., New Caledonia",
		UTC:    []string{"Antarctica/Macquarie", "Etc/GMT-11", "Pacific/Efate", "Pacific/Guadalcanal", "Pacific/Kosrae", "Pacific/Noumea", "Pacific/Ponape"},
	},
	{
		Value:  "Vladivostok Standard Time",
		Abbr:   "VLAT",
		Offset: 10,
		IsDST:  false,
		Text:   "(UTC+10:00) Vladivostok",
		UTC:    []string{"Asia/Ust-Nera", "Asia/Vladivostok"},
	},
	{
		Value:  "Sakhalin Standard Time",
		Abbr:   "SAKT",
		Offset: 11,
		IsDST:  false,
		Text:   "(UTC+11:00) Sakhalin",
		UTC:    []string{"Asia/Sakhalin"},
	},
	{
		Value:  "New Zealand Standard Time",
		Abbr:   "NZST",
		Offset: 12,
		IsDST:  false,
		Text:   "(UTC+12:00) Auckland, Wellington",
		UTC:    []string{"Antarctica/McMurdo", "Pacific/Auckland"},
	},
	{
		Value:  "UTC+12",
		Abbr:   "U",
		Offset: 12,
		IsDST:  false,
		Text:   "(UTC+12:00) Coordinated Universal Time+12",
		UTC:    []string{"Etc/GMT-12", "Pacific/Funafuti", "Pacific/Kwajalein", "Pacific/Majuro", "Pacific/Nauru", "Pacific/Tarawa", "Pacific/Wake", "Pacific/Wallis"},
	},
	{
		Value:  "Fiji Standard Time",
		Abbr:   "FST",
		Offset: 12,
		IsDST:  false,
		Text:   "(UTC+12:00) Fiji",
		UTC:    []string{"Pacific/Fiji"},
	},
	{
		Value:  "Magadan Standard Time",
		Abbr:   "MST",
		Offset: 12,
		IsDST:  false,
		Text:   "(UTC+12:00) Magadan",
		UTC:    []string{"Asia/Anadyr", "Asia/Kamchatka", "Asia/Magadan", "Asia/Srednekolymsk"},
	},
	{
		Value:  "Kamchatka Standard Time",
		Abbr:   "KDT",
		Offset: 13,
		IsDST:  true,
		Text:   "(UTC+12:00) Petropavlovsk-Kamchatsky - Old",
		UTC:    []string{"Asia/Kamchatka"},
	},
	{
		Value:  "Tonga Standard Time",
		Abbr:   "TST",
		Offset: 13,
		IsDST:  false,
		Text:   "(UTC+13:00) Nuku'alofa",
		UTC:    []string{"Etc/GMT-13", "Pacific/Enderbury", "Pacific/Fakaofo", "Pacific/Tongatapu"},
	},
	{
		Value:  "Samoa Standard Time",
		Abbr:   "SST",
		Offset: 13,
		IsDST:  false,
		Text:   "(UTC+13:00) Samoa",
		UTC:    []string{"Pacific/Apia"},
	},
}
