package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"math/big"
	"os"
	"regexp"
	"sort"
	"strings"
)

type operation struct {
	DocumentID            string `json:"documentId"`
	Kind                  string `json:"kind"`
	ResponseDiscriminator string `json:"responseDiscriminator"`
}

type spec struct {
	SourceRevision string               `json:"sourceRevision"`
	WAVersion      string               `json:"waVersion"`
	Operations     map[string]operation `json:"operations"`
}

var (
	hexRevision = regexp.MustCompile(`^[0-9a-f]{40}$`)
	goName      = regexp.MustCompile(`^[A-Z][A-Za-z0-9]*$`)
)

func main() {
	input := flag.String("input", "mex/spec.json", "input specification")
	output := flag.String("output", "mex/bindings.go", "generated Go file")
	check := flag.Bool("check", false, "fail when output differs")
	flag.Parse()

	data, err := os.ReadFile(*input)
	checkErr(err)
	var parsed spec
	checkErr(json.Unmarshal(data, &parsed))
	checkErr(validate(parsed))
	generated, err := render(parsed)
	checkErr(err)

	if *check {
		current, err := os.ReadFile(*output)
		checkErr(err)
		if !bytes.Equal(current, generated) {
			checkErr(fmt.Errorf("%s is not generated from %s", *output, *input))
		}
		return
	}
	checkErr(os.WriteFile(*output, generated, 0o644))
}

func validate(parsed spec) error {
	if !hexRevision.MatchString(parsed.SourceRevision) {
		return fmt.Errorf("invalid source revision %q", parsed.SourceRevision)
	}
	if strings.TrimSpace(parsed.WAVersion) == "" {
		return fmt.Errorf("missing WhatsApp Web version")
	}
	if len(parsed.Operations) == 0 {
		return fmt.Errorf("no operations")
	}
	for name, op := range parsed.Operations {
		if !goName.MatchString(name) {
			return fmt.Errorf("invalid operation name %q", name)
		}
		id, ok := new(big.Int).SetString(op.DocumentID, 10)
		if !ok || id.Sign() <= 0 {
			return fmt.Errorf("invalid document ID for %s", name)
		}
		if op.Kind != "query" && op.Kind != "mutation" {
			return fmt.Errorf("invalid operation kind %q for %s", op.Kind, name)
		}
		if strings.TrimSpace(op.ResponseDiscriminator) == "" {
			return fmt.Errorf("missing response discriminator for %s", name)
		}
	}
	return nil
}

func render(parsed spec) ([]byte, error) {
	names := make([]string, 0, len(parsed.Operations))
	for name := range parsed.Operations {
		names = append(names, name)
	}
	sort.Strings(names)

	var out strings.Builder
	out.WriteString("// Code generated by internal/cmd/genmex; DO NOT EDIT.\n\n")
	out.WriteString("package mex\n\n")
	out.WriteString("type OperationName string\n\n")
	out.WriteString("type OperationKind string\n\n")
	out.WriteString("const (\n\tKindQuery OperationKind = \"query\"\n\tKindMutation OperationKind = \"mutation\"\n)\n\n")
	fmt.Fprintf(&out, "const SourceRevision = %q\n\n", parsed.SourceRevision)
	fmt.Fprintf(&out, "const WebVersion = %q\n\n", parsed.WAVersion)
	out.WriteString("const (\n")
	for _, name := range names {
		fmt.Fprintf(&out, "\t%s OperationName = %q\n", name, name)
	}
	out.WriteString(")\n\n")
	out.WriteString("type Operation struct {\n\tName OperationName\n\tDocumentID string\n\tKind OperationKind\n\tResponseDiscriminator string\n}\n\n")
	out.WriteString("var operations = map[OperationName]Operation{\n")
	for _, name := range names {
		op := parsed.Operations[name]
		kind := "KindQuery"
		if op.Kind == "mutation" {
			kind = "KindMutation"
		}
		fmt.Fprintf(&out, "\t%s: {Name: %s, DocumentID: %q, Kind: %s, ResponseDiscriminator: %q},\n", name, name, op.DocumentID, kind, op.ResponseDiscriminator)
	}
	out.WriteString("}\n\n")
	out.WriteString("func Lookup(name OperationName) (Operation, bool) {\n\top, ok := operations[name]\n\treturn op, ok\n}\n")
	return format.Source([]byte(out.String()))
}

func checkErr(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
